<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        User::truncate();

        $user = [
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Algeria',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Algeria',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Egypt',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Egypt',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Ghana',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Ghana',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => 'Nelson',
                'last_name' => 'Mendela',
                'user_name' => 'nelsonM',
                'country' => 'South Africa',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => 'Abraham',
                'last_name' => 'De Villiars',
                'user_name' => 'ABD360',
                'country' => 'South Africa',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Zimbabwe',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Zimbabwe',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => 'Ananta',
                'last_name' => 'Jalil',
                'user_name' => 'AJSuperstar',
                'country' => 'Bangladesh',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => 'Shakib',
                'last_name' => 'Al Hasan',
                'user_name' => 'Shakib75',
                'country' => 'Bangladesh',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => 'Pori',
                'last_name' => 'Moni',
                'user_name' => 'danakatapori',
                'country' => 'Bangladesh',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'China',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'China',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => 'Mahendra',
                'last_name' => 'Singh Dhoni',
                'user_name' => 'MSDcaptaincool',
                'country' => 'India',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => 'Katrina',
                'last_name' => 'Kaif',
                'user_name' => 'kkaif123',
                'country' => 'India',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => 'Mia',
                'last_name' => 'Khalifa',
                'user_name' => 'merealMK00',
                'country' => 'Lebanon',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Lebanon',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'United Arab Emirates',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'United Arab Emirates',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => 'Karim',
                'last_name' => 'Benzema',
                'user_name' => 'bigboykb',
                'country' => 'France',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => 'Melanie',
                'last_name' => 'Laurent',
                'user_name' => 'shoshanna83',
                'country' => 'France',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' =>'Mesut',
                'last_name' => 'Ozil',
                'user_name' => 'playmaker10',
                'country' => 'Germany',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => 'Toni',
                'last_name' => 'Kroos',
                'user_name' => 'germansniper08',
                'country' => 'Germany',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Italy',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Italy',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Spain',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Spain',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => 'Gemma',
                'last_name' => 'Arterton',
                'user_name' => 'pollytamina',
                'country' => 'United Kingdom',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => 'Sherlock',
                'last_name' => 'Holmes',
                'user_name' => 'acdholmes',
                'country' => 'United Kingdom',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Bahamas',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Bahamas',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Barbados',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Barbados',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Costa Rica',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Costa Rica',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Cuba',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Cuba',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Dominica',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Dominica',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Australia',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Australia',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Fiji',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Fiji',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'New Zealand',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'New Zealand',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Papua New Guinea',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Papua New Guinea',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Samoa',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Samoa',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Argentina',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Argentina',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Brazil',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Brazil',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Colombia',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Colombia',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Ecudaor',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Ecudaor',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Venezuela',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ],
            [
                'first_name' => Str::random(15),
                'last_name' => Str::random(15),
                'user_name' => Str::random(10),
                'country' => 'Venezuela',
                'email' => Str::random(10).'@gmail.com',
                'password' => Hash::make('password'),
            ]
        ];
        User::insert($user);
    }
}
